name: Lint (Go)

on:
  push:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/lint-go.yml"
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/lint-go.yml"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.17"  # Cambiá si tu go.mod usa otra versión

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m
