name: Lint (Python)

on:
  push:
    paths:
      - "**/*.py"
      - ".flake8"
      - ".github/workflows/lint-python.yml"
  pull_request:
    paths:
      - "**/*.py"
      - ".flake8"
      - ".github/workflows/lint-python.yml"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 .
